version: '3'

services:

  php: &php
    build: .
    volumes:
      - .:/app
      - ./.tmp/.composer:/.composer
      - ./.tmp/.composer:/root/.composer

  composer: { <<: *php, entrypoint: ["composer"] }

  phpunit: { <<: *php, entrypoint: ["/app/vendor/bin/phpunit"] }
