version: '3'

services:

  php: &php
    build: .
    volumes:
      - .:/app
      - ./.tmp:/root

  composer: { <<: *php, entrypoint: ["composer"] }

  phpunit: { <<: *php, entrypoint: ["/app/vendor/bin/phpunit"] }
